modules:
  robot:
    JointStatePerceptionModule: pepper_joints
  humans:
    OptitrackPerceptionModule: optitrack_1
    StampedPosePerceptionModule: human
  objects:
    ArTrackPerceptionModule: ar_track
    StaticObjectsPerceptionModule: static

pepper_joints:
  robot_name : pepper

optitrack_1:
  name: human_1
  offset_x: 6.4868
  offset_y: 2.8506
  #offset_x: 6.5068
  #offset_y: 2.9506
  offset_z: 0.16

human:
  name: human_0

ar_track:
  min_track_err: 0.05
  sensor_id: realsense

static:
  file: package://overworld/config/adream.yaml